# Mount kubeshare on each cluster node as a file share.
---
- name: Mount kubeshare
  hosts: all
  # gather_facts: false
  become: true
  vars_prompt:
    - name: sshfs_user
      prompt: "Enter sshfs mount user"
      private: false
    - name: sshfs_password
      prompt: "Enter sshfs mount password"
    - name: sshfs_host
      prompt: "Enter sshfs host"      
  vars_files:
    - vars/vars_vault.yaml
  vars:
    ansible_ssh_password: "{{ kc_ssh_password }}"
    ansible_become_password: "{{ kc_become_password }}"
    mount_host: "{{ sshfs_host }}"
    mount_source_path: "{{ sshfs_user }}@{{ mount_host }}:/home/{{ sshfs_user }}/kubeshare"
    mount_dest_path: "/home/localsysadmin/kubeshare"
  tasks:
    # - name: Debug print mounts
    #   ansible.builtin.debug:
    #     msg: '{{ ansible_mounts | selectattr("mount", "equalto", "/") | list | length > 0 }}'
    - name: Include mount sshfs
      ansible.builtin.include_role:
        name: kcsup
        tasks_from: mount_kubeshare_sshfs
