# Copy the kubeconfig from one node to other nodes
---
- name: Get kubeconfig
  hosts: all
  gather_facts: true
  become: true
  vars_prompt:
   - name: copy_from_hostname
     prompt: "Enter host to copy kubeconfig from"
     private: false
  vars_files:
   - vars/vars_vault.yaml
  vars:
   ansible_ssh_password: "{{ kc_ssh_password }}"
   ansible_become_password: "{{ kc_become_password }}"
  tasks:
   - name: Get kubeconfig
     ansible.builtin.fetch:
      src: /root/.kube/config
      dest: "~/kubeconfig_from_{{ copy_from_hostname }}"
      flat: true
     delegate_to: "{{ copy_from_hostname }}"
#
   - name: Check for /root/.kube
     ansible.builtin.stat:
      path: /root/.kube
      get_checksum: false
      get_mime: false
     register: dotkube_stat
   - name: Create /root/.kube
     ansible.builtin.file:
      state: directory
      path: /root/.kube
      owner: root
      group: root
      mode: "0755"
     when: not dotkube_stat.stat.exists
   - name: Copy kubeconfig
     ansible.builtin.copy:
      src: "~/kubeconfig_from_{{ copy_from_hostname }}"
      dest: /root/.kube/config
      owner: root
      group: root
      mode: "0600"
