- name: Ping hosts
  hosts: all
  serial: 1
  gather_facts: false
  become: true
  vars_files:
   - vars/vars_vault.yaml
  vars:
    ansible_ssh_password: "{{ kc_ssh_password }}"
    ansible_become_password: "{{ kc_become_password }}"
  tasks:
  - name: Remove ssh host keys
    delegate_to: localhost
    become: false
    ansible.builtin.command:
      cmd: "ssh-keygen -R {{ inventory_hostname }}"
  - name: Ping host
    ping:
