---
- name: Get kubernets cluster facts
  hosts: all
  gather_facts: false
  become: true
  vars_files:
    - vars/vars_vault.yaml
  vars_prompt:
    - name: kc_control_name
      prompt: "Kubernetes control node hostname: "
      private: false
  vars:
    ansible_ssh_password: "{{ kc_ssh_password }}"
    ansible_become_password: "{{ kc_become_password }}"
  tasks:
    - name: Store kc_control_name in hostvar container
      ansible.builtin.add_host:
        name: "K8S_VARS"
        kc_control_name: "{{ kc_control_name }}"
    - name: Get cluster facts
      ansible.builtin.include_role:
        name: kcfacts
        tasks_from: kc_get_facts
    - name: Debug print hostvars["K8S_VARS"]
      ansible.builtin.debug:
        var: hostvars["K8S_VARS"]
        verbosity: 1
