# Install metrics server
---
- name: Install metrics server
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - vars/vars_vault.yaml
  vars:
    ansible_ssh_password: "{{ kc_ssh_password }}"
    ansible_become_password: "{{ kc_become_password }}"
  tasks:
# Install metrics
    - name: Install metrics
      ansible.builtin.include_role:
        name: kcsetup_inet
        tasks_from: apply_metrics.yaml
