# (Attempt to) cleanup host networking configuration so kubeinit can be run again.
# This is not always going to be successful. The host may need to be rebooted.
---
# Reset firewall. This will require restarting crio and kublet to rebuild their rules.
- name: Reset linux firewall rules
  when: false
  block:
    # RHEL 9 is nftables with iptables (the program) in nft mode.
    # - name: Reset iptables
    #   command: "{{ item }}"
    #   with_items:
    #     - iptables -F
    #     - iptables -X
    #     - iptables -t nat -F
    #     - iptables -t nat -X
    #     - iptables -t mangle -F
    #     - iptables -t mangle -X
    #     # - ipvsadm -C # Not installed
    - name: Reset nftables
      command: "{{ item }}"
      with_items:
        - nft flush ruleset
