# This is used to delete files left on the host node after kubeadm reset.
# kubectl delete -f manifest.yaml may delete them, but that would delete the
# manifest from the entire cluster.
---
- name: Delete default bridge host-local
  when: cluster_net_default == "bridge_hl"
  block:
    - name: Delete default bridge IPAM host-local CNI config
      ansible.builtin.file:
        path: /etc/cni/net.d/20-ipv4-bridge-hl.conflist
        state: absent
- name: Delete default bridge DHCP
  when: cluster_net_default == "bridge_dhcp"
  block:
    - name: Disable cni-dhcp service
      ansible.builtin.systemd:
        daemon_reload: true
        name: cni-dhcp
        enabled: false
        state: stopped
    - name: Delete service file for DHCP CNI server
      ansible.builtin.file:
        path: /etc/systemd/system/cni-dhcp.service
        state: absent
    - name: Delete default bridge IPAM DHCP CNI config
      ansible.builtin.file:
        path: /etc/cni/net.d/20-ipv4-bridge-dhcp.conflist
        state: absent
- name: Delete default macvlan DHCP
  when: cluster_net_default == "macvlan_dhcp"
  block:
    - name: Disable cni-dhcp service
      ansible.builtin.systemd:
        daemon_reload: true
        name: cni-dhcp
        enabled: false
        state: stopped
    - name: Delete service file for DHCP CNI server
      ansible.builtin.file:
        path: /etc/systemd/system/cni-dhcp.service
        state: absent
    - name: Delete default macvlan IPAM DHCP CNI config
      ansible.builtin.file:
        path: /etc/cni/net.d/20-ipv4-macvlan-dhcp.conflist
        state: absent
- name: Use default bridge calico
  when: cluster_net_default == "calico"
  block:
    - name: Copy default calico CNI config
      ansible.builtin.debug:
        msg: "Calico has its own delete playbook"
# Delete multus files
- name: Delete /opt/cni/bin/multus
  ansible.builtin.file:
    state: absent
    path: /opt/cni/bin/multus
- name: Delete /opt/cni/bin/multus-shim
  ansible.builtin.file:
    state: absent
    path: /opt/cni/bin/multus-shim
- name: Delete /etc/cni/net.d/00-multus.conf
  ansible.builtin.file:
    state: absent
    path: /etc/cni/net.d/00-multus.conf
