# This is used to delete files left on the host node after kubeadm reset.
# Files that kubectl delete -f manifest.yaml does not remove.
---
# Delete the host-local and DHCP configuration
- name: Delete default bridge host-local
  when: cluster_net_default == "bridge_hl"
  block:
    - name: Delete default bridge IPAM host-local CNI config
      ansible.builtin.file:
        path: /etc/cni/net.d/20-ipv4-bridge-hl.conflist
        state: absent
- name: Delete default bridge DHCP
  when: cluster_net_default == "bridge_dhcp"
  block:
    - name: Disable cni-dhcp service
      ansible.builtin.systemd:
        daemon_reload: true
        name: cni-dhcp
        enabled: false
        state: stopped
    - name: Delete service file for DHCP CNI server
      ansible.builtin.file:
        path: /etc/systemd/system/cni-dhcp.service
        state: absent
    - name: Delete default bridge IPAM DHCP CNI config
      ansible.builtin.file:
        path: /etc/cni/net.d/20-ipv4-bridge-dhcp.conflist
        state: absent
- name: Delete default bridge whereabouts
  when: cluster_net_default == "bridge_whereabouts"
  block:
    - name: Delete default bridge IPAM whereabouts CNI config
      ansible.builtin.file:
        path: /etc/cni/net.d/20-ipv4-bridge-whereabouts.conflist
        state: absent
- name: Delete default macvlan DHCP
  when: cluster_net_default == "macvlan_dhcp"
  block:
    - name: Disable cni-dhcp service
      ansible.builtin.systemd:
        daemon_reload: true
        name: cni-dhcp
        enabled: false
        state: stopped
    - name: Delete service file for DHCP CNI server
      ansible.builtin.file:
        path: /etc/systemd/system/cni-dhcp.service
        state: absent
    - name: Delete default macvlan IPAM DHCP CNI config
      ansible.builtin.file:
        path: /etc/cni/net.d/20-ipv4-macvlan-dhcp.conflist
        state: absent
# Delete calico CNI files
- name: Delete default CNI calico
  when: cluster_net_default == "calico"
  block:
    - name: Run delete_calico
      ansible.builtin.include_role:
        name: kcsetup_inet
        tasks_from: delete_calico
# Delete cilium CNI files
- name: Delete default CNI cilium
  when: cluster_net_default == "cilium"
  block:
    - name: Run delete_cilium
      ansible.builtin.include_role:
        name: kcsetup_inet
        tasks_from: delete_cilium
# Delete multus CNI files
- name: Delete /opt/cni/bin/multus
  ansible.builtin.file:
    state: absent
    path: /opt/cni/bin/multus
- name: Delete /opt/cni/bin/multus-shim
  ansible.builtin.file:
    state: absent
    path: /opt/cni/bin/multus-shim
- name: Delete /etc/cni/net.d/00-multus.conf
  ansible.builtin.file:
    state: absent
    path: /etc/cni/net.d/00-multus.conf
# Delete whereabouts CNI files
- name: Delete whereabouts CNI files
  when: cluster_install_whereabouts
  block:
    - name: Delete whereabouts files
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /opt/cni/bin/whereabouts
        - /etc/cni/net.d/whereabouts.d
