# Deleting calico CNI will royaly screw up the cluster networking.
# Likely all pod networking will stop working.
# Expect to reboot cluster nodes to remove things like disconnected interfaces,
# orphan eBPF, and nftables rules.
#
# Assume this is run after kubeadm reset.
# Reinstalling (any) CNI without kubeadm reset has not been explored.
---
# - name: Delete calico manifest
#   ansible.builtin.command:
#     cmd: kubectl delete -f /root/kubeinit/calico/calico-v3.27.2.yaml
- name: Remove calico NetworkManager unmanaged-devices conf
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /etc/NetworkManager/conf/calico.conf
    - /etc/cni/net.d/10-calico.conflist
    - /etc/cni/net.d/calico-kubeconfig
    - /opt/cni/bin/calico
    - /opt/cni/bin/calico-ipam
    - /var/log/calico
# Calico-node container replaced, in /opt/cni/bin, bandwidth, host-local, loopback, portmap, and tuning
- name: Reinstall kubernetes CNI
  ansible.builtin.command: dnf reinstall -y --disableexcludes kubernetes kubernetes-cni
