- name: Create /root/kubeinit
  ansible.builtin.file:
    state: directory
    path: /root/kubeinit
    owner: root
    group: root
    mode: "0750"
- name: Copy kubeadm-config.yaml
  ansible.builtin.template:
    src: kube/kubeadm-config.yaml.j2
    dest: /root/kubeinit/kubeadm-config.yaml
    owner: root
    group: root
    mode: "0640"
# Don't start kubeadm init when images aren't available
- name: Run kubeadm config images pull
  shell:
    cmd: kubeadm -v 4 config images pull --config /root/kubeinit/kubeadm-config.yaml 2>&1
  register: kubeadm_config_images_pull_result
  failed_when: false
- name: Save kubeadm config images pull stdout
  ansible.builtin.copy:
    content: "{{ kubeadm_config_images_pull_result.stdout }}"
    dest: /root/kubeinit/kubeadm_config_images_pull_stdout.txt
    owner: root
    group: root
    mode: "0600"
- name: Fail if kubeadm config images pull failed
  fail:
    msg: "kubeadm config images pull failed"
  when: kubeadm_config_images_pull_result.rc != 0
- name: Run kubeadm init
  shell:
    cmd: kubeadm init -v 4 --config /root/kubeinit/kubeadm-config.yaml 2>&1
  register: kubeadm_init_result
  failed_when: false
- name: Save kubeadm init stdout
  ansible.builtin.copy:
    content: "{{ kubeadm_init_result.stdout }}"
    dest: /root/kubeinit/kubeadm_init_stdout.txt
    owner: root
    group: root
    mode: "0600"
- name: Fail if kubeadm init failed
  fail:
    msg: "kubeadm init failed"
  when: kubeadm_init_result.rc != 0
- name: Check for /root/.kube
  ansible.builtin.stat:
    path: /root/.kube
    get_checksum: false
    get_mime: false
  register: dotkube_stat
- name: Create /root/.kube
  ansible.builtin.file:
    state: directory
    path: /root/.kube
    owner: root
    group: root
    mode: "0755"
  when: not dotkube_stat.stat.exists
- name: Copy admin kubeconfig to /root/.kube/config
  ansible.builtin.copy:
    remote_src: true
    backup: true
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root
    mode: "0600"
