---
- name: Delete multus manifest
  ansible.builtin.command:
    cmd: kubectl delete -f /root/kubeinit/multus/multus-daemonset-thick-v4.0.2.yaml
# Delete multus files
- name: Delete /opt/cni/bin/multus
  ansible.builtin.file:
    state: absent
    path: /opt/cni/bin/multus
- name: Delete /opt/cni/bin/multus-shim
  ansible.builtin.file:
    state: absent
    path: /opt/cni/bin/multus-shim
- name: Delete /etc/cni/net.d/00-multus.conf
  ansible.builtin.file:
    state: absent
    path: /etc/cni/net.d/00-multus.conf
