# kubectl apply -f https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset-thick.yml
# Change the image tag from snapshot-thick to v4.1.0-thick
# In the kube-multus-ds DaemonSet The kube-multus container gets OOMKilled. Change reservation to 100mi.
---
# Delete stale config files
- name: Delete /opt/cni/bin/multus
  ansible.builtin.file:
    state: absent
    path: /opt/cni/bin/multus
- name: Delete /opt/cni/bin/multus-shim
  ansible.builtin.file:
    state: absent
    path: /opt/cni/bin/multus-shim
- name: Delete /etc/cni/net.d/00-multus.conf
  ansible.builtin.file:
    state: absent
    path: /etc/cni/net.d/00-multus.conf
# Copy over manifests
- name: Create kubeinit/multus
  ansible.builtin.file:
    state: directory
    path: /root/kubeinit/multus
    owner: root
    group: root
    mode: "0640"
- name: Copy multus manifest
  ansible.builtin.copy:
    src: multus/multus-daemonset-thick-v4.1.0.yaml
    dest: /root/kubeinit/multus/multus-daemonset-thick-v4.1.0.yaml
    owner: root
    group: root
    mode: "0640"
