# Remove the control plane taint from a node so it can run worker pods
---
- name: Remove control plane taint
  hosts: all
  gather_facts: false
  become: true
  vars_files:
    - vars/vars_vault.yaml
  vars:
    ansible_ssh_password: "{{ kc_ssh_password }}"
    ansible_become_password: "{{ kc_become_password }}"
  tasks:
    - name: Remove control plane taint
      ansible.builtin.command: "kubectl taint nodes {{ inventory_hostname_short }} node-role.kubernetes.io/control-plane-"
      changed_when: true
