# Remove the control plane taint from a node so it can run worker pods
# Remove the exclude external load balancers label so LoadBalancers can expose services
---
- name: Allow control plane to run worker loads
  hosts: all
  gather_facts: false
  become: true
  vars_files:
    - vars/vars_vault.yaml
  vars:
    ansible_ssh_password: "{{ kc_ssh_password }}"
    ansible_become_password: "{{ kc_become_password }}"
  tasks:
    - name: Remove control plane taint
      ansible.builtin.command: "kubectl taint nodes {{ inventory_hostname_short }} node-role.kubernetes.io/control-plane-"
      changed_when: true
    - name: Remove control plane exclude from external LoadBalancers label
      ansible.builtin.command: "kubectl label node {{ inventory_hostname_short }} node.kubernetes.io/exclude-from-external-load-balancers-"
      changed_when: true
